syntax = "proto3";

package production;

message ProductionItem {
  string ma_cong_trinh = 1;
  string ten_cong_trinh = 2;
  int64 hex = 3;
  string tinh_trang_ipo = 4;
  string tinh_trang_du_an = 5;
  string ghi_chu = 6;
  string ten_pm = 7;
  string ten_pc = 8;
  string ngay_nhan_tu_pm = 9;
  string ngay_can = 10;
  string ngay_can_giao = 11;
  string bot_du_an = 12;
  string khach_hang = 13;
  int64 so_ipo = 14;
  int64 ma_id_sap = 15;
  int64 ma_nha_may = 16;
  string ten_hang_muc = 17;
  string phan_loai_nhom_san_pham = 18;
  string ghi_chu_don_hang_tong = 19;
  string tam_ngung_huy_don_hang_tong = 20;
  string mo_ta_san_pham = 21;
  string khu_vuc = 22;
  string khu_vuc_du_an = 23;
  string ma_hang_muc_boq = 24;
  string ma_boq = 25;
  string wbs_cap_2 = 26;
  string xuong_chinh = 27;
  string dvt = 28;
  double don_gia_co_oh = 29;
  double so_luong_don_hang_tong = 30;
  double tri_gia_don_hang_tong = 31;
  double so_luong_tinh_phieu = 32;
  double thanh_tien_tinh_phieu = 33;
  double so_luong_nhap_kho_luy_ke = 34;
  double thanh_tien_nhap_kho_luy_ke = 35;
  double so_luong_xuat_kho_luy_ke = 36;
  double thanh_tien_xuat_kho_luy_ke = 37;
  double so_luong_ton_kho_hien_tai = 38;
  double thanh_tien_ton_kho_hien_tai = 39;
  double so_luong_con_lai = 40;
  double gia_tri_con_lai = 41;
  double so_luong_don_hang_con_lai = 42;
  double gia_tri_don_hang_con_lai = 43;
  string tong_hop_ghi_chu_nhap_kho = 44;
  string tong_hop_thong_tin_qc = 45;
  string tong_hop_ghi_chu_xuat_kho = 46;
  string dau_hieu_nhap_kho_khong_dong_bo = 47;
  string tinh_trang_trien_khai_ban_ve = 48;
  string ngay_trien_khai_ban_ve = 49;
  string nguoi_trien_khai_ban_ve = 50;
  string tinh_trang_phieu = 51;
  string ngay_tinh_phieu = 52;
  string ngay_duyet_phieu = 53;
  string ghi_chu_phieu = 54;
  string xuong_phu_tro = 55;
  string nvl_go_tam_veneer_khac = 56;
  string tinh_trang_nvl_khac_item_by_item = 57;
  string co_vecni = 58;
  string nvl_vecni = 59;
  string co_sofa = 60;
  string nvl_sofa = 61;
  string tinh_trang_nvl_sofa_item_by_item = 62;
  string cd_x_sofa = 63;
  string co_kim_loai = 64;
  string nvl_kim_loai = 65;
  string cd_x_kim_loai = 66;
  string co_kinh_da = 67;
  string nvl_kinh_da = 68;
  string tinh_trang_nvl_kinh_da_item_by_item = 69;
  string cd_x_da = 70;
  string tinh_trang_nvl_kinh_chua_ve_gop_theo_ct = 71;
  string tinh_trang_nvl_da_chua_ve_gop_theo_ct = 72;
  string tinh_trang_nvl_sofa_chua_ve_gop_theo_ct = 73;
  string co_gia_cong_ngoai = 74;
  string tinh_trang_gcn = 75;
  string tinh_trang_gcn_chua_ve = 76;
  string xuong_yeu_cau_gcn = 77;
  string ngay_du_kien_ve_gcn = 78;
  string trang_thai_gcn = 79;
  double so_luong_cong_doan_cts_da_giao = 80;
  double so_luong_cong_doan_may_da_giao = 81;
  double so_luong_cong_doan_moc_da_giao = 82;
  double so_luong_cong_doan_vecni_da_giao = 83;
  double so_luong_cong_doan_fitting_da_giao = 84;
  double so_luong_cong_doan_kim_loai_da_giao = 85;
  double so_luong_cong_doan_sofa_da_giao = 86;
  double so_luong_cong_doan_da_da_giao = 87;
  double so_luong_cong_doan_kinh_da_giao = 88;
  double so_luong_cong_doan_bao_bi_da_giao = 89;
  string tinh_trang = 90;
  string bop = 91;
  string ngay_khnk_thang = 92;
  double sl_khnk_thang = 93;
  double gt_khnk_thang = 94;
  string ngay_khnk_tuan = 95;
  double sl_khnk_tuan = 96;
  double gt_khnk_tuan = 97;
  string ghi_chu_khnk = 98;
  string nhom_ct = 99;
  string so_ngay_cd_hien_tai = 100;
  string vai_goi = 101;
  string ct_uu_tien = 102;
}

message ProductionResponse {
  repeated ProductionItem items = 1;
}