import {TARGET_COLUMN_NAMES } from '../../types.ts';

export const STATUS_GROUPS = {
  CO_THE_SX: [
    '01. NHẬP KHO KĐB', '02. BAO BÌ', '02.1. ĐÓNG KIỆN',
    '03. FITTING', '03.3. FITTING KL',
    '04. VECNI', '04.1. BỌC NỆM', '04.2. PVD',
    '05. MỘC', '05.1. TỔ ĐÁ', '05.2. NGUỘI',
    '06. MÁY', '06.1. HÀN',
    '07. CTS', '07.1. CTS ĐÁ', '07.2. PHÔI', '07.ĐÃ GIAO GCNB',
    '11. CHƯA SX',
    '16. GIA CÔNG VỆ TINH-BTP', '16.1. GIA CÔNG VỆ TINH-NGUYÊN CON',
    '16.2. GIA CÔNG VỆ TINH-ĐÁ', '16.3. GIA CÔNG VỆ TINH-KHÁC'
  ],
  VECNI_FITTING: [
    '01. NHẬP KHO KĐB', '02. BAO BÌ', '02.1. ĐÓNG KIỆN'
  ],
  CHUYEN_KHAC: [
    '03. FITTING', '03.3. FITTING KL',
    '04. VECNI', '04.1. BỌC NỆM', '04.2. PVD',
    '05. MỘC', '05.1. TỔ ĐÁ', '05.2. NGUỘI',
    '06. MÁY', '06.1. HÀN',
    '07. CTS', '07.1. CTS ĐÁ', '07.2. PHÔI', '07.ĐÃ GIAO GCNB',
    '16. GIA CÔNG VỆ TINH-BTP', '16.1. GIA CÔNG VỆ TINH-NGUYÊN CON',
    '16.2. GIA CÔNG VỆ TINH-ĐÁ', '16.3. GIA CÔNG VỆ TINH-KHÁC'
  ],
  CO_PHIEU_CHUA_SX: [
    '11. CHƯA SX'
  ],
  CHUA_THE_SX: [
    '12. CHƯA SX PHẦN CÒN LẠI', '13. CHƯA PHIẾU PHẦN CÒN LẠI',
    '14. CHƯA PHIẾU', '14.1. CHƯA PHIẾU KL', '15. CHƯA TRIỂN KHAI'
  ],
  VUONG_SL: [
    '12. CHƯA SX PHẦN CÒN LẠI', '13. CHƯA PHIẾU PHẦN CÒN LẠI'
  ],
  CHUA_TRIEN_KHAI: [
    '14. CHƯA PHIẾU', '14.1. CHƯA PHIẾU KL', '15. CHƯA TRIỂN KHAI'
  ]
};

export const MATERIAL_LIST_COLUMNS = [
  TARGET_COLUMN_NAMES.STATUS,
  TARGET_COLUMN_NAMES.CONG_TRINH,
  TARGET_COLUMN_NAMES.SO_PR,
  TARGET_COLUMN_NAMES.TEN_VAT_TU,
  TARGET_COLUMN_NAMES.SL_YEU_CAU,
  TARGET_COLUMN_NAMES.BASE_UNIT,
  TARGET_COLUMN_NAMES.REQUEST_DATE,
  TARGET_COLUMN_NAMES.EST_DELIVERY,
  TARGET_COLUMN_NAMES.SL_DA_NHAN,
  TARGET_COLUMN_NAMES.REMAINING_QTY,
  TARGET_COLUMN_NAMES.TEAM_PR_NOTE,
  TARGET_COLUMN_NAMES.STATUS_PO,
  TARGET_COLUMN_NAMES.NOTE_PO,
  TARGET_COLUMN_NAMES.PR_ITEM,
  TARGET_COLUMN_NAMES.ACTUAL_DATE,
  TARGET_COLUMN_NAMES.ACTUAL_QTY,
  TARGET_COLUMN_NAMES.MATERIAL_CODE,
  TARGET_COLUMN_NAMES.REQUISITIONER,

];

export const MATERIAL_LIST_COLUMN_LABELS: Record<string, string> = {
  [TARGET_COLUMN_NAMES.STATUS]: 'TRẠNG THÁI',
  [TARGET_COLUMN_NAMES.CONG_TRINH]: 'TÊN CÔNG TRÌNH',
  [TARGET_COLUMN_NAMES.SO_PR]: 'SỐ PR',
  [TARGET_COLUMN_NAMES.TEN_VAT_TU]: 'TÊN VẬT TƯ',
  [TARGET_COLUMN_NAMES.SL_YEU_CAU]: 'SỐ LƯỢNG YÊU CẦU',
  [TARGET_COLUMN_NAMES.BASE_UNIT]: 'ĐVT',
  [TARGET_COLUMN_NAMES.REQUEST_DATE]: 'NGÀY PR',
  [TARGET_COLUMN_NAMES.EST_DELIVERY]: 'NGÀY DỰ KIẾN GIAO HÀNG PMH NHẬP',
  [TARGET_COLUMN_NAMES.SL_DA_NHAN]: 'SỐ LƯỢNG ĐÃ NHẬN (SAP)',
  [TARGET_COLUMN_NAMES.REMAINING_QTY]: 'SỐ LƯỢNG CÒN LẠI',
  [TARGET_COLUMN_NAMES.TEAM_PR_NOTE]: 'TEAM PR NOTE',
  [TARGET_COLUMN_NAMES.STATUS_PO]: 'TÌNH TRẠNG PO',
  [TARGET_COLUMN_NAMES.NOTE_PO]: 'GHI CHÚ TÌNH TRẠNG PO',
  [TARGET_COLUMN_NAMES.PR_ITEM]: 'PR LINE',
  [TARGET_COLUMN_NAMES.ACTUAL_DATE]: 'NGÀY VỀ - KHO BÁO',
  [TARGET_COLUMN_NAMES.ACTUAL_QTY]: 'SL HÀNG VỀ THỰC TẾ - KHO BÁO',
  [TARGET_COLUMN_NAMES.MATERIAL_CODE]: 'MÃ VẬT TƯ (SAP)',
  [TARGET_COLUMN_NAMES.REQUISITIONER]: 'NGƯỜI YÊU CẦU',
};